name: Test Self-Hosted

on:
  workflow_dispatch: 

jobs:
  curl:
    name: Curl
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Hacer una solicitud a Google
        run: |
          echo "Haciendo una solicitud a Google..."
          curl https://www.google.com

  job2:
    name: Trabajo 2
    runs-on: self-hosted
    steps:
      - name: Paso 1
        run: echo "Este es el paso 1 del trabajo 3"
      - name: Paso 2
        run: echo "Este es el paso 2 del trabajo 3"
      - name: Paso 3
        run: echo "Este es el paso 3 del trabajo 3"

